name: zap_client
description: A client for Zap server or Zap Adapters, this is part of ZapTools Proyect
version: 0.0.3
repository: https://github.com/NathanDraco22/zap-client-dart


environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  web_socket_channel: ^2.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
